name: Demo CI/CD - 3rd

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build Gradle
        working-directory: "."
        run: |
          chmod +x gradlew
          ./gradlew build --exclude-task test
      - name: Run Tests
        working-directory: "."
        run: |
          ./gradlew test